from treelib import Node, Tree

tree = Tree()

tree.create_node("Are you hungry?", "root_ques", data="")  # root node

tree.create_node("No", "1_no", parent="root_ques", data="Have a nice day!")
tree.create_node("Yes", "1_yes", parent="root_ques", data="Which state do you live in?")

# tree.create_node("Have a nice day!", "1_no_end", parent="1_no")

# tree.create_node("Which state do you live in?", "2_state", parent="1_yes")

tree.create_node("Alabama", "alabama", parent="1_yes", data="Which city do you live in?")
tree.create_node("Alaska", "alaska", parent="1_yes", data="Which city do you live in?")
tree.create_node("Arizona", "arizona", parent="1_yes", data="Which city do you live in?")
tree.create_node("Arkansas", "arkansas", parent="1_yes", data="Which city do you live in?")
tree.create_node("California", "california", parent="1_yes", data="Which city do you live in?")
tree.create_node("Colorado", "colorado", parent="1_yes", data="Which city do you live in?")
tree.create_node("Connecticut", "connecticut", parent="1_yes", data="Which city do you live in?")
tree.create_node("District of Columbia", "district_of_columbia", parent="1_yes", data="Which city do you live in?")
tree.create_node("Florida", "florida", parent="1_yes", data="Which city do you live in?")
tree.create_node("Georgia", "georgia", parent="1_yes", data="Which city do you live in?")
tree.create_node("Hawaii", "hawaii", parent="1_yes", data="Which city do you live in?")
tree.create_node("Idaho", "idaho", parent="1_yes", data="Which city do you live in?")
tree.create_node("Illinois", "illinois", parent="1_yes", data="Which city do you live in?")
tree.create_node("Indiana", "indiana", parent="1_yes", data="Which city do you live in?")
tree.create_node("Iowa", "iowa", parent="1_yes", data="Which city do you live in?")
tree.create_node("Kansas", "kansas", parent="1_yes", data="Which city do you live in?")
tree.create_node("Kentucky", "kentucky", parent="1_yes", data="Which city do you live in?")
tree.create_node("Louisiana", "louisiana", parent="1_yes", data="Which city do you live in?")
tree.create_node("Maryland", "maryland", parent="1_yes", data="Which city do you live in?")
tree.create_node("Massachusetts", "massachusetts", parent="1_yes", data="Which city do you live in?")
tree.create_node("Michigan", "michigan", parent="1_yes", data="Which city do you live in?")
tree.create_node("Minnesota", "minnesota", parent="1_yes", data="Which city do you live in?")
tree.create_node("Mississippi", "mississippi", parent="1_yes", data="Which city do you live in?")
tree.create_node("Missouri", "missouri", parent="1_yes", data="Which city do you live in?")
tree.create_node("Montana", "montana", parent="1_yes", data="Which city do you live in?")
tree.create_node("Nebraska", "nebraska", parent="1_yes", data="Which city do you live in?")
tree.create_node("Nevada", "nevada", parent="1_yes", data="Which city do you live in?")
tree.create_node("New Hampshire", "new_hampshire", parent="1_yes", data="Which city do you live in?")
tree.create_node("New Jersey", "new_jersey", parent="1_yes", data="Which city do you live in?")
tree.create_node("New Mexico", "new_mexico", parent="1_yes", data="Which city do you live in?")
tree.create_node("New York", "new_york", parent="1_yes", data="Which city do you live in?")
tree.create_node("North Carolina", "north_carolina", parent="1_yes", data="Which city do you live in?")
tree.create_node("North Dakota", "north_dakota", parent="1_yes", data="Which city do you live in?")
tree.create_node("Ohio", "ohio", parent="1_yes", data="Which city do you live in?")
tree.create_node("Oklahoma", "oklahoma", parent="1_yes", data="Which city do you live in?")
tree.create_node("Oregon", "oregon", parent="1_yes", data="Which city do you live in?")
tree.create_node("Pennsylvania", "pennsylvania", parent="1_yes", data="Which city do you live in?")
tree.create_node("Rhode Island", "rhode_island", parent="1_yes", data="Which city do you live in?")
tree.create_node("South Carolina", "south_carolina", parent="1_yes", data="Which city do you live in?")
tree.create_node("South Dakota", "south_dakota", parent="1_yes", data="Which city do you live in?")
tree.create_node("Tennessee", "tennessee", parent="1_yes", data="Which city do you live in?")
tree.create_node("Texas", "texas", parent="1_yes", data="Which city do you live in?")
tree.create_node("Utah", "utah", parent="1_yes", data="Which city do you live in?")
tree.create_node("Virginia", "virginia", parent="1_yes", data="Which city do you live in?")
tree.create_node("Washington", "washington", parent="1_yes", data="Which city do you live in?")
tree.create_node("Wisconsin", "wisconsin", parent="1_yes", data="Which city do you live in?")


tree.create_node("Birmingham", "alabama_birmingham", parent="alabama", data="")
tree.create_node("Montgomery", "alabama_montgomery", parent="alabama", data="")
tree.create_node("Huntsville", "alabama_huntsville", parent="alabama", data="")
tree.create_node("Mobile", "alabama_mobile", parent="alabama", data="")
tree.create_node("Tuscaloosa", "alabama_tuscaloosa", parent="alabama", data="")
tree.create_node("Anchorage", "alaska_anchorage", parent="alaska", data="")
tree.create_node("Phoenix", "arizona_phoenix", parent="arizona", data="")
tree.create_node("Tucson", "arizona_tucson", parent="arizona", data="")
tree.create_node("Mesa", "arizona_mesa", parent="arizona", data="")
tree.create_node("Chandler", "arizona_chandler", parent="arizona", data="")
tree.create_node("Scottsdale", "arizona_scottsdale", parent="arizona", data="")
tree.create_node("Glendale", "arizona_glendale", parent="arizona", data="")
tree.create_node("Gilbert", "arizona_gilbert", parent="arizona", data="")
tree.create_node("Tempe", "arizona_tempe", parent="arizona", data="")
tree.create_node("Peoria", "arizona_peoria", parent="arizona", data="")
tree.create_node("Surprise", "arizona_surprise", parent="arizona", data="")
tree.create_node("Little Rock", "arkansas_littlerock", parent="arkansas", data="")
tree.create_node("Los Angeles", "california_losangeles", parent="california", data="")
tree.create_node("San Diego", "california_sandiego", parent="california", data="")
tree.create_node("San Jose", "california_sanjose", parent="california", data="")
tree.create_node("San Francisco", "california_sanfrancisco", parent="california", data="")
tree.create_node("Fresno", "california_fresno", parent="california", data="")
tree.create_node("Sacramento", "california_sacramento", parent="california", data="")
tree.create_node("Long Beach", "california_longbeach", parent="california", data="")
tree.create_node("Oakland", "california_oakland", parent="california", data="")
tree.create_node("Bakersfield", "california_bakersfield", parent="california", data="")
tree.create_node("Anaheim", "california_anaheim", parent="california", data="")
tree.create_node("Santa Ana", "california_santaana", parent="california", data="")
tree.create_node("Riverside", "california_riverside", parent="california", data="")
tree.create_node("Stockton", "california_stockton", parent="california", data="")
tree.create_node("Irvine", "california_irvine", parent="california", data="")
tree.create_node("Chula Vista", "california_chulavista", parent="california", data="")
tree.create_node("Fremont", "california_fremont", parent="california", data="")
tree.create_node("San Bernardino", "california_sanbernardino", parent="california", data="")
tree.create_node("Modesto", "california_modesto", parent="california", data="")
tree.create_node("Fontana", "california_fontana", parent="california", data="")
tree.create_node("Santa Clarita", "california_santaclarita", parent="california", data="")
tree.create_node("Oxnard", "california_oxnard", parent="california", data="")
tree.create_node("Moreno Valley", "california_morenovalley", parent="california", data="")
tree.create_node("Glendale", "california_glendale", parent="california", data="")
tree.create_node("Huntington Beach", "california_huntingtonbeach", parent="california", data="")
tree.create_node("Ontario", "california_ontario", parent="california", data="")
tree.create_node("Rancho Cucamonga", "california_ranchocucamonga", parent="california", data="")
tree.create_node("Santa Rosa", "california_santarosa", parent="california", data="")
tree.create_node("Oceanside", "california_oceanside", parent="california", data="")
tree.create_node("Elk Grove", "california_elkgrove", parent="california", data="")
tree.create_node("Garden Grove", "california_gardengrove", parent="california", data="")
tree.create_node("Corona", "california_corona", parent="california", data="")
tree.create_node("Hayward", "california_hayward", parent="california", data="")
tree.create_node("Lancaster", "california_lancaster", parent="california", data="")
tree.create_node("Palmdale", "california_palmdale", parent="california", data="")
tree.create_node("Salinas", "california_salinas", parent="california", data="")
tree.create_node("Sunnyvale", "california_sunnyvale", parent="california", data="")
tree.create_node("Pomona", "california_pomona", parent="california", data="")
tree.create_node("Escondido", "california_escondido", parent="california", data="")
tree.create_node("Torrance", "california_torrance", parent="california", data="")
tree.create_node("Pasadena", "california_pasadena", parent="california", data="")
tree.create_node("Fullerton", "california_fullerton", parent="california", data="")
tree.create_node("Orange", "california_orange", parent="california", data="")
tree.create_node("Roseville", "california_roseville", parent="california", data="")
tree.create_node("Visalia", "california_visalia", parent="california", data="")
tree.create_node("Concord", "california_concord", parent="california", data="")
tree.create_node("Santa Clara", "california_santaclara", parent="california", data="")
tree.create_node("Thousand Oaks", "california_thousandoaks", parent="california", data="")
tree.create_node("Simi Valley", "california_simivalley", parent="california", data="")
tree.create_node("Victorville", "california_victorville", parent="california", data="")
tree.create_node("Vallejo", "california_vallejo", parent="california", data="")
tree.create_node("Berkeley", "california_berkeley", parent="california", data="")
tree.create_node("Fairfield", "california_fairfield", parent="california", data="")
tree.create_node("Carlsbad", "california_carlsbad", parent="california", data="")
tree.create_node("El Monte", "california_elmonte", parent="california", data="")
tree.create_node("Murrieta", "california_murrieta", parent="california", data="")
tree.create_node("Temecula", "california_temecula", parent="california", data="")
tree.create_node("Costa Mesa", "california_costamesa", parent="california", data="")
tree.create_node("Downey", "california_downey", parent="california", data="")
tree.create_node("Clovis", "california_clovis", parent="california", data="")
tree.create_node("Antioch", "california_antioch", parent="california", data="")
tree.create_node("Ventura", "california_ventura", parent="california", data="")
tree.create_node("Richmond", "california_richmond", parent="california", data="")
tree.create_node("Inglewood", "california_inglewood", parent="california", data="")
tree.create_node("Jurupa Valley", "california_jurupavalley", parent="california", data="")
tree.create_node("Santa Maria", "california_santamaria", parent="california", data="")
tree.create_node("Daly City", "california_dalycity", parent="california", data="")
tree.create_node("West Covina", "california_westcovina", parent="california", data="")
tree.create_node("Norwalk", "california_norwalk", parent="california", data="")
tree.create_node("San Mateo", "california_sanmateo", parent="california", data="")
tree.create_node("Burbank", "california_burbank", parent="california", data="")
tree.create_node("Rialto", "california_rialto", parent="california", data="")
tree.create_node("El Cajon", "california_elcajon", parent="california", data="")
tree.create_node("Vista", "california_vista", parent="california", data="")
tree.create_node("Vacaville", "california_vacaville", parent="california", data="")
tree.create_node("Denver", "colorado_denver", parent="colorado", data="")
tree.create_node("Colorado Springs", "colorado_coloradosprings", parent="colorado", data="")
tree.create_node("Aurora", "colorado_aurora", parent="colorado", data="")
tree.create_node("Fort Collins", "colorado_fortcollins", parent="colorado", data="")
tree.create_node("Lakewood", "colorado_lakewood", parent="colorado", data="")
tree.create_node("Thornton", "colorado_thornton", parent="colorado", data="")
tree.create_node("Arvada", "colorado_arvada", parent="colorado", data="")
tree.create_node("Westminster", "colorado_westminster", parent="colorado", data="")
tree.create_node("Pueblo", "colorado_pueblo", parent="colorado", data="")
tree.create_node("Centennial", "colorado_centennial", parent="colorado", data="")
tree.create_node("Boulder", "colorado_boulder", parent="colorado", data="")
tree.create_node("Greeley", "colorado_greeley", parent="colorado", data="")
tree.create_node("Bridgeport", "connecticut_bridgeport", parent="connecticut", data="")
tree.create_node("New Haven", "connecticut_newhaven", parent="connecticut", data="")
tree.create_node("Stamford", "connecticut_stamford", parent="connecticut", data="")
tree.create_node("Hartford", "connecticut_hartford", parent="connecticut", data="")
tree.create_node("Waterbury", "connecticut_waterbury", parent="connecticut", data="")
tree.create_node("Washington", "district_of_columbia_washington", parent="district_of_columbia", data="")
tree.create_node("Jacksonville", "florida_jacksonville", parent="florida", data="")
tree.create_node("Miami", "florida_miami", parent="florida", data="")
tree.create_node("Tampa", "florida_tampa", parent="florida", data="")
tree.create_node("Orlando", "florida_orlando", parent="florida", data="")
tree.create_node("St. Petersburg", "florida_stpetersburg", parent="florida", data="")
tree.create_node("Hialeah", "florida_hialeah", parent="florida", data="")
tree.create_node("Port St. Lucie", "florida_portstlucie", parent="florida", data="")
tree.create_node("Tallahassee", "florida_tallahassee", parent="florida", data="")
tree.create_node("Cape Coral", "florida_capecoral", parent="florida", data="")
tree.create_node("Fort Lauderdale", "florida_fortlauderdale", parent="florida", data="")
tree.create_node("Pembroke Pines", "florida_pembrokepines", parent="florida", data="")
tree.create_node("Hollywood", "florida_hollywood", parent="florida", data="")
tree.create_node("Miramar", "florida_miramar", parent="florida", data="")
tree.create_node("Gainesville", "florida_gainesville", parent="florida", data="")
tree.create_node("Coral Springs", "florida_coralsprings", parent="florida", data="")
tree.create_node("Clearwater", "florida_clearwater", parent="florida", data="")
tree.create_node("Palm Bay", "florida_palmbay", parent="florida", data="")
tree.create_node("Miami Gardens", "florida_miamigardens", parent="florida", data="")
tree.create_node("Pompano Beach", "florida_pompanobeach", parent="florida", data="")
tree.create_node("West Palm Beach", "florida_westpalmbeach", parent="florida", data="")
tree.create_node("Lakeland", "florida_lakeland", parent="florida", data="")
tree.create_node("Davie", "florida_davie", parent="florida", data="")
tree.create_node("Augusta", "georgia_augusta", parent="georgia", data="")
tree.create_node("Atlanta", "georgia_atlanta", parent="georgia", data="")
tree.create_node("Columbus", "georgia_columbus", parent="georgia", data="")
tree.create_node("Macon", "georgia_macon", parent="georgia", data="")
tree.create_node("Savannah", "georgia_savannah", parent="georgia", data="")
tree.create_node("Athens", "georgia_athens", parent="georgia", data="")
tree.create_node("Sandy Springs", "georgia_sandysprings", parent="georgia", data="")
tree.create_node("Honolulu", "hawaii_honolulu", parent="hawaii", data="")
tree.create_node("Boise", "idaho_boise", parent="idaho", data="")
tree.create_node("Meridian", "idaho_meridian", parent="idaho", data="")
tree.create_node("Chicago", "illinois_chicago", parent="illinois", data="")
tree.create_node("Aurora", "illinois_aurora", parent="illinois", data="")
tree.create_node("Naperville", "illinois_naperville", parent="illinois", data="")
tree.create_node("Joliet", "illinois_joliet", parent="illinois", data="")
tree.create_node("Rockford", "illinois_rockford", parent="illinois", data="")
tree.create_node("Springfield", "illinois_springfield", parent="illinois", data="")
tree.create_node("Elgin", "illinois_elgin", parent="illinois", data="")
tree.create_node("Peoria", "illinois_peoria", parent="illinois", data="")
tree.create_node("Indianapolis", "indiana_indianapolis", parent="indiana", data="")
tree.create_node("Fort Wayne", "indiana_fortwayne", parent="indiana", data="")
tree.create_node("Evansville", "indiana_evansville", parent="indiana", data="")
tree.create_node("South Bend", "indiana_southbend", parent="indiana", data="")
tree.create_node("Des Moines", "iowa_desmoines", parent="iowa", data="")
tree.create_node("Cedar Rapids", "iowa_cedarrapids", parent="iowa", data="")
tree.create_node("Davenport", "iowa_davenport", parent="iowa", data="")
tree.create_node("Wichita", "kansas_wichita", parent="kansas", data="")
tree.create_node("Overland Park", "kansas_overlandpark", parent="kansas", data="")
tree.create_node("Kansas City", "kansas_kansascity", parent="kansas", data="")
tree.create_node("Olathe", "kansas_olathe", parent="kansas", data="")
tree.create_node("Topeka", "kansas_topeka", parent="kansas", data="")
tree.create_node("Louisville", "kentucky_louisville", parent="kentucky", data="")
tree.create_node("Lexington", "kentucky_lexington", parent="kentucky", data="")
tree.create_node("New Orleans", "louisiana_neworleans", parent="louisiana", data="")
tree.create_node("Baton Rouge", "louisiana_batonrouge", parent="louisiana", data="")
tree.create_node("Shreveport", "louisiana_shreveport", parent="louisiana", data="")
tree.create_node("Lafayette", "louisiana_lafayette", parent="louisiana", data="")
tree.create_node("Baltimore", "maryland_baltimore", parent="maryland", data="")
tree.create_node("Boston", "massachusetts_boston", parent="massachusetts", data="")
tree.create_node("Worcester", "massachusetts_worcester", parent="massachusetts", data="")
tree.create_node("Springfield", "massachusetts_springfield", parent="massachusetts", data="")
tree.create_node("Cambridge", "massachusetts_cambridge", parent="massachusetts", data="")
tree.create_node("Lowell", "massachusetts_lowell", parent="massachusetts", data="")
tree.create_node("Detroit", "michigan_detroit", parent="michigan", data="")
tree.create_node("Grand Rapids", "michigan_grandrapids", parent="michigan", data="")
tree.create_node("Warren", "michigan_warren", parent="michigan", data="")
tree.create_node("Sterling Heights", "michigan_sterlingheights", parent="michigan", data="")
tree.create_node("Ann Arbor", "michigan_annarbor", parent="michigan", data="")
tree.create_node("Lansing", "michigan_lansing", parent="michigan", data="")
tree.create_node("Clinton", "michigan_clinton", parent="michigan", data="")
tree.create_node("Minneapolis", "minnesota_minneapolis", parent="minnesota", data="")
tree.create_node("Saint Paul", "minnesota_saintpaul", parent="minnesota", data="")
tree.create_node("Rochester", "minnesota_rochester", parent="minnesota", data="")
tree.create_node("Jackson", "mississippi_jackson", parent="mississippi", data="")
tree.create_node("Kansas City", "missouri_kansascity", parent="missouri", data="")
tree.create_node("St. Louis", "missouri_stlouis", parent="missouri", data="")
tree.create_node("Springfield", "missouri_springfield", parent="missouri", data="")
tree.create_node("Columbia", "missouri_columbia", parent="missouri", data="")
tree.create_node("Independence", "missouri_independence", parent="missouri", data="")
tree.create_node("Billings", "montana_billings", parent="montana", data="")
tree.create_node("Omaha", "nebraska_omaha", parent="nebraska", data="")
tree.create_node("Lincoln", "nebraska_lincoln", parent="nebraska", data="")
tree.create_node("Las Vegas", "nevada_lasvegas", parent="nevada", data="")
tree.create_node("Henderson", "nevada_henderson", parent="nevada", data="")
tree.create_node("Reno", "nevada_reno", parent="nevada", data="")
tree.create_node("North Las Vegas", "nevada_northlasvegas", parent="nevada", data="")
tree.create_node("Sparks", "nevada_sparks", parent="nevada", data="")
tree.create_node("Manchester", "new_hampshire_manchester", parent="new_hampshire", data="")
tree.create_node("Newark", "new_jersey_newark", parent="new_jersey", data="")
tree.create_node("Jersey City", "new_jersey_jerseycity", parent="new_jersey", data="")
tree.create_node("Paterson", "new_jersey_paterson", parent="new_jersey", data="")
tree.create_node("Elizabeth", "new_jersey_elizabeth", parent="new_jersey", data="")
tree.create_node("Lakewood", "new_jersey_lakewood", parent="new_jersey", data="")
tree.create_node("Edison", "new_jersey_edison", parent="new_jersey", data="")
tree.create_node("Woodbridge", "new_jersey_woodbridge", parent="new_jersey", data="")
tree.create_node("Albuquerque", "new_mexico_albuquerque", parent="new_mexico", data="")
tree.create_node("Las Cruces", "new_mexico_lascruces", parent="new_mexico", data="")
tree.create_node("New York", "new_york_newyork", parent="new_york", data="")
tree.create_node("Buffalo", "new_york_buffalo", parent="new_york", data="")
tree.create_node("Rochester", "new_york_rochester", parent="new_york", data="")
tree.create_node("Yonkers", "new_york_yonkers", parent="new_york", data="")
tree.create_node("Syracuse", "new_york_syracuse", parent="new_york", data="")
tree.create_node("Charlotte", "north_carolina_charlotte", parent="north_carolina", data="")
tree.create_node("Raleigh", "north_carolina_raleigh", parent="north_carolina", data="")
tree.create_node("Greensboro", "north_carolina_greensboro", parent="north_carolina", data="")
tree.create_node("Durham", "north_carolina_durham", parent="north_carolina", data="")
tree.create_node("Winston–Salem", "north_carolina_winstonsalem", parent="north_carolina", data="")
tree.create_node("Fayetteville", "north_carolina_fayetteville", parent="north_carolina", data="")
tree.create_node("Cary", "north_carolina_cary", parent="north_carolina", data="")
tree.create_node("Wilmington", "north_carolina_wilmington", parent="north_carolina", data="")
tree.create_node("High Point", "north_carolina_highpoint", parent="north_carolina", data="")
tree.create_node("Fargo", "north_dakota_fargo", parent="north_dakota", data="")
tree.create_node("Columbus", "ohio_columbus", parent="ohio", data="")
tree.create_node("Cleveland", "ohio_cleveland", parent="ohio", data="")
tree.create_node("Cincinnati", "ohio_cincinnati", parent="ohio", data="")
tree.create_node("Toledo", "ohio_toledo", parent="ohio", data="")
tree.create_node("Akron", "ohio_akron", parent="ohio", data="")
tree.create_node("Dayton", "ohio_dayton", parent="ohio", data="")
tree.create_node("Oklahoma City", "oklahoma_oklahomacity", parent="oklahoma", data="")
tree.create_node("Tulsa", "oklahoma_tulsa", parent="oklahoma", data="")
tree.create_node("Norman", "oklahoma_norman", parent="oklahoma", data="")
tree.create_node("Broken Arrow", "oklahoma_brokenarrow", parent="oklahoma", data="")
tree.create_node("Portland", "oregon_portland", parent="oregon", data="")
tree.create_node("Salem", "oregon_salem", parent="oregon", data="")
tree.create_node("Eugene", "oregon_eugene", parent="oregon", data="")
tree.create_node("Gresham", "oregon_gresham", parent="oregon", data="")
tree.create_node("Hillsboro", "oregon_hillsboro", parent="oregon", data="")
tree.create_node("Philadelphia", "pennsylvania_philadelphia", parent="pennsylvania", data="")
tree.create_node("Pittsburgh", "pennsylvania_pittsburgh", parent="pennsylvania", data="")
tree.create_node("Allentown", "pennsylvania_allentown", parent="pennsylvania", data="")
tree.create_node("Providence", "rhode_island_providence", parent="rhode_island", data="")
tree.create_node("Charleston", "south_carolina_charleston", parent="south_carolina", data="")
tree.create_node("Columbia", "south_carolina_columbia", parent="south_carolina", data="")
tree.create_node("North Charleston", "south_carolina_northcharleston", parent="south_carolina", data="")
tree.create_node("Sioux Falls", "south_dakota_siouxfalls", parent="south_dakota", data="")
tree.create_node("Nashville", "tennessee_nashville", parent="tennessee", data="")
tree.create_node("Memphis", "tennessee_memphis", parent="tennessee", data="")
tree.create_node("Knoxville", "tennessee_knoxville", parent="tennessee", data="")
tree.create_node("Chattanooga", "tennessee_chattanooga", parent="tennessee", data="")
tree.create_node("Clarksville", "tennessee_clarksville", parent="tennessee", data="")
tree.create_node("Murfreesboro", "tennessee_murfreesboro", parent="tennessee", data="")
tree.create_node("Houston", "texas_houston", parent="texas", data="")
tree.create_node("San Antonio", "texas_sanantonio", parent="texas", data="")
tree.create_node("Dallas", "texas_dallas", parent="texas", data="")
tree.create_node("Austin", "texas_austin", parent="texas", data="")
tree.create_node("Fort Worth", "texas_fortworth", parent="texas", data="")
tree.create_node("El Paso", "texas_elpaso", parent="texas", data="")
tree.create_node("Arlington", "texas_arlington", parent="texas", data="")
tree.create_node("Corpus Christi", "texas_corpuschristi", parent="texas", data="")
tree.create_node("Plano", "texas_plano", parent="texas", data="")
tree.create_node("Laredo", "texas_laredo", parent="texas", data="")
tree.create_node("Lubbock", "texas_lubbock", parent="texas", data="")
tree.create_node("Garland", "texas_garland", parent="texas", data="")
tree.create_node("Irving", "texas_irving", parent="texas", data="")
tree.create_node("Amarillo", "texas_amarillo", parent="texas", data="")
tree.create_node("Grand Prairie", "texas_grandprairie", parent="texas", data="")
tree.create_node("McKinney", "texas_mckinney", parent="texas", data="")
tree.create_node("Frisco", "texas_frisco", parent="texas", data="")
tree.create_node("Brownsville", "texas_brownsville", parent="texas", data="")
tree.create_node("Pasadena", "texas_pasadena", parent="texas", data="")
tree.create_node("Killeen", "texas_killeen", parent="texas", data="")
tree.create_node("McAllen", "texas_mcallen", parent="texas", data="")
tree.create_node("Mesquite", "texas_mesquite", parent="texas", data="")
tree.create_node("Midland", "texas_midland", parent="texas", data="")
tree.create_node("Denton", "texas_denton", parent="texas", data="")
tree.create_node("Waco", "texas_waco", parent="texas", data="")
tree.create_node("Carrollton", "texas_carrollton", parent="texas", data="")
tree.create_node("Round Rock", "texas_roundrock", parent="texas", data="")
tree.create_node("Abilene", "texas_abilene", parent="texas", data="")
tree.create_node("Pearland", "texas_pearland", parent="texas", data="")
tree.create_node("Richardson", "texas_richardson", parent="texas", data="")
tree.create_node("Odessa", "texas_odessa", parent="texas", data="")
tree.create_node("Sugar Land", "texas_sugarland", parent="texas", data="")
tree.create_node("Beaumont", "texas_beaumont", parent="texas", data="")
tree.create_node("College Station", "texas_collegestation", parent="texas", data="")
tree.create_node("Lewisville", "texas_lewisville", parent="texas", data="")
tree.create_node("League City", "texas_leaguecity", parent="texas", data="")
tree.create_node("Tyler", "texas_tyler", parent="texas", data="")
tree.create_node("Wichita Falls", "texas_wichitafalls", parent="texas", data="")
tree.create_node("Allen", "texas_allen", parent="texas", data="")
tree.create_node("San Angelo", "texas_sanangelo", parent="texas", data="")
tree.create_node("Salt Lake City", "utah_saltlakecity", parent="utah", data="")
tree.create_node("West Valley City", "utah_westvalleycity", parent="utah", data="")
tree.create_node("Provo", "utah_provo", parent="utah", data="")
tree.create_node("West Jordan", "utah_westjordan", parent="utah", data="")
tree.create_node("Virginia Beach", "virginia_virginiabeach", parent="virginia", data="")
tree.create_node("Norfolk", "virginia_norfolk", parent="virginia", data="")
tree.create_node("Chesapeake", "virginia_chesapeake", parent="virginia", data="")
tree.create_node("Richmond", "virginia_richmond", parent="virginia", data="")
tree.create_node("Newport News", "virginia_newportnews", parent="virginia", data="")
tree.create_node("Alexandria", "virginia_alexandria", parent="virginia", data="")
tree.create_node("Hampton", "virginia_hampton", parent="virginia", data="")
tree.create_node("Seattle", "washington_seattle", parent="washington", data="")
tree.create_node("Spokane", "washington_spokane", parent="washington", data="")
tree.create_node("Tacoma", "washington_tacoma", parent="washington", data="")
tree.create_node("Vancouver", "washington_vancouver", parent="washington", data="")
tree.create_node("Bellevue", "washington_bellevue", parent="washington", data="")
tree.create_node("Kent", "washington_kent", parent="washington", data="")
tree.create_node("Everett", "washington_everett", parent="washington", data="")
tree.create_node("Renton", "washington_renton", parent="washington", data="")
tree.create_node("Milwaukee", "wisconsin_milwaukee", parent="wisconsin", data="")
tree.create_node("Madison", "wisconsin_madison", parent="wisconsin", data="")
tree.create_node("Green Bay", "wisconsin_greenbay", parent="wisconsin", data="")
tree.create_node("Kenosha", "wisconsin_kenosha", parent="wisconsin", data="")  


# tree.show() 



node  = tree.get_node("root_ques")
subtree = tree.subtree("root_ques")
children = subtree.children("root_ques")

while True:
    print(node.tag)
    if node.data!="":
        print(node.data)
    if len(children) == 0:
        print("Thank you!")
        break
        
    for i, idx_node in enumerate(children):
        print("%d. %s" % (i, idx_node.tag))
    if len(children) == 1:
        userinput = 0
    else:
        userinput = int(input("Select index: "))
    node_id = children[userinput].identifier
    node = tree.get_node(node_id)
    subtree = tree.subtree(node_id)
    children = subtree.children(node_id)
